#include "table.h"

std::array<std::size_t, TPCH_TABLE_COUNT> TPCH_TABLE_COLUMN_COUNT = {
  CUSTOMER_TABLE_COL_CNT,
  LINEITEM_TABLE_COL_CNT,
  NATION_TABLE_COL_CNT,
  ORDERS_TABLE_COL_CNT,
  PART_TABLE_COL_CNT,
  PARTSUPP_TABLE_COL_CNT,
  REGION_TABLE_COL_CNT,
  SUPPLIER_TABLE_COL_CNT
};
